name: gapura_emas
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/anjab.png
    - assets/apik.png
    - assets/banner.jpg
    - assets/butam.png
    - assets/gapura.png
    - assets/hallo.png
    - assets/logo-pasuruan.png
    - assets/logosepakat.png
    - assets/logosmart.png
    - assets/majestik.png
    - assets/pastipaskabbot.png
    - assets/sakti.png
    - assets/sapa.png
    - assets/saraswati.png
    - assets/sepakat.png
    - assets/sikap.png
    - assets/smart.png
    - assets/spbe.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
